const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: './images/item-2.jpeg',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: './images/item-4.jpeg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: './images/item-5.jpeg',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'karnıyarık',
    category: 'dinner',
    price: 19.99,
    img: './images/item-7.jpeg',
    desc: `Karnıyarık Türk mutfağının belli başlı patlıcan yemeklerinden biridir. Hazırlanırken ana malzeme olan patlıcanın dışında soğan, biber, domates ve kıyma da kullanılır. `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: './images/item-8.jpeg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: './images/item-9.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 10,
    title: 'Menemen',
    category: 'breakfast',
    price: 16.99,
    img: './images/item-10.jpeg',
    desc: `
  Menemen, yumurta, biber, domates ve isteğe bağlı olarak soğan kullanılarak yapılan bir Türk yemeğidir. İlk kez mübadele ile İzmir'in Menemen ilçesine gelen Girit Türkleri tarafından yapılmıştır ve adını ilçeden almaktadır.`,
  },
  {
    id: 11,
    title: 'Makarna',
    category: 'dinner',
    price: 16.99,
    img: './images/item-11.jpeg',
    desc: `En çok kullanılan öğrenci yemeği. kolay yapım az yanma ve ziyan tehlikesi. pişirirkene ağzını yarım açmak lazım yoksa taşıyo`,
  },
  {
    id: 12,
    title: 'Ekşili Köfte',
    category: 'dinner',
    price: 22.99,
    img: './images/item-12.jpeg',
    desc: `içinde havuç,patates,köfte bulunan lezzet patlaması ve şifa deposu çorba.terbiyesi yapılmalıdır.yemeden önce karabiber eklenmesi tavsiye edilir.`,
  },
];
export default menu;
